apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
spec:
  selector:
    matchLabels:
      app: go-service
  replicas: 1
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
      - name: go-service
        image: ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
